export default [
    {
        id: 'datagrid',
        title: 'Datagrid',
        properties: ['React', 'Redux', 'material-ui'],
        repLink: 'https://github.com/aykuli/datagrid/tree/datagrid',
        deploy: 'https://aykuli.github.io/datagrid/',
    },
    {
        id: 'belarus-writers',
        title: 'Belarus Writers',
        properties: ['Gatsby', 'material-ui', 'Typescript', 'Storybook', 'adaptive up to 320px'],
        repLink: 'https://github.com/aykuli/belarus-writers',
        deploy: 'https://belarusian-writers.netlify.com/',
    },
    {
        id: 'fancy-weather',
        title: 'Fancy Weather',
        properties: ['JS', 'API: mapbox, darksky.net, ipinfo.io, opencagedata.com, unsplash.com', 'Jest, jsdom testing','adaptive up to 320px'],
        repLink: 'https://github.com/aykuli/fancy-weather/',
        deploy: 'https://aykuli.github.io/fancy-weather/',
    },
    {
        id: 'songbird',
        title: 'Songbird quiz',
        properties: ['React'],
        repLink: 'https://github.com/aykuli/songbird/tree/songbird/',
        deploy: 'https://aykuli.github.io/songbird/',
    },
    {
        id: 'piskel-clone',
        title: 'Piskel Clone',
        properties: ['JS', 'Jest, jsdom testing','simplified piskelapp.com',],
        repLink: 'https://github.com/aykuli/piskel-clone/',
        deploy: 'https://aykuli.github.io/piskel-clone/',
    },
    {
        id: 'virtual-keyboard',
        title: 'Virtual Keyboard',
        properties: ['JS'],
        repLink: 'https://github.com/aykuli/codejam-virtual-keyboard/',
        deploy: 'https://aykuli.github.io/codejam-virtual-keyboard/',
    },
    {
        id: 'image-api',
        title: 'Image Api',
        properties: ['JS'],
        repLink: 'https://github.com/aykuli/image-api/',
        deploy: 'https://aykuli.github.io/image-api/',
    },
    {
        id: 'meme-generator',
        title: 'Meme Generator',
        properties: ['React', 'JS'],
        repLink: 'https://github.com/aykuli/meme-generator/',
        deploy: 'https://aykuli.github.io/meme-generator/',
    },
    {
        id: 'todo-redux',
        title: 'ToDo App',
        properties: ['React', 'Redux', 'JS'],
        repLink: 'https://github.com/aykuli/todo-react-second/',
        deploy: 'https://aykuli.github.io/todo-react-second/',
    },
    {
        id: 'repair-design-project',
        title: 'Repair Design Project',
        properties: ['JS', 'CSS3', 'HTML'],
        repLink: 'https://github.com/aykuli/repair-design-project/',
        deploy: 'https://aykuli.github.io/repair-design-project/',
    },
    {
        id: 'halbstadt',
        title: 'Halbstadt.info',
        properties: ['Drupal CMS'],
        repLink: 0,
        deploy: 'http://halbstadt.info/',
    },
    {
        id: 'gllasy',
        title: 'Glassy',
        properties: ['JS', 'CSS3', 'HTML'],
        repLink: 'https://github.com/aykuli/gllacy-base-23/',
        deploy: 'https://aykuli.github.io/gllacy-base-23/index.html',
    },
    {
        id: 'welcome-landmark',
        title: 'Welcome Landmark',
        properties: ['React'],
        repLink: 'https://github.com/aykuli/welcome-landmark',
        deploy: 'https://aykuli.github.io/welcome-landmark/',
    },
    {
        id: 'chuck-norris',
        title: 'Joke generator',
        properties: ['JS'],
        repLink: 'https://github.com/aykuli/Chuck-NorrisJoke-Generator/',
        deploy: 'https://aykuli.github.io/Chuck-NorrisJoke-Generator/',
    },
    {
        id: 'tic-tac-toe-react',
        title: 'Tic-Tac-Toe on React',
        properties: ['React', 'JS'],
        repLink: 'https://github.com/aykuli/tic-tac-toe-react/',
        deploy: 'https://aykuli.github.io/tic-tac-toe-react/',
    },
    {
        id: 'product-filter',
        title: 'Pproduct Filter on React',
        properties: ['React', 'JS'],
        repLink: 'https://github.com/aykuli/product-filter/',
        deploy: 'https://aykuli.github.io/product-filter/',
    },
]